### ISSUE TITLE
[Workaround] Disable LOG(fatal) stack traces for FairRoot 18.6

### ISSUE THREAD

**Issue by klenze** [FairRootGroup/FairRoot#1201] opened 2022-06-14 23:25 UTC
If a LOG(fatal) is executed somewhere, FairRoot 18.6 will still unconditionally try to make ROOT dump a stack trace and -- adding insult to injury -- still mislabel it as a core dump. 

Luckily, fair::Logger::OnFatal can be used to replace the handler with a less noisy one. 
The trick here is to make sure that the singleton FairLogger (which assigns the fatal handler) is already created before we reassign that. 

The simpler way to do that is to use, somewhere before your LOG(fatal) appears:
```
  FairLogger::GetLogger();
  fair::Logger::OnFatal([]{throw std::runtime_error("LoggedError");});
```

To fix this project-wide is a bit more tricky but can be done without resorting to LD_PRELOAD. 

In any compile unit, place:
```
int NO_STACKTRACE=[]()
{ 
  FairLogger::GetLogger();
  fair::Logger::OnFatal([]{throw std::runtime_error("LoggedError");});
  return 0;
}();
```

By dynamically initializing a global variable, we make sure that our code is run before main() is even started. (FairLogger::instance is constant-initialized to nullptr. No Static Initialization Order Fiasco here.)

In related news, getting a useful stack trace (and much more) is dead simple. Just run the program in a debugger of your choice, e.g. gdb. If you are running a root macro, try running gdb --args root.exe myMacro.C
(Of course, backtraces will only help you if the troublesome code is compiled in a normal way. If it is instead included inline in a LinkDef or defined in a macro, you are out of luck, as the call stack line for a root macro function looks like ``#14 0x00007ffff7e2b4a1 in ?? ()``. Did you really think you could just interpret C++ without having to pay a price? The proper way to run a root macro is to compile it to a normal binary first.)

**Comment by dennisklein** [comment] 2022-06-15 01:25
duplicate of #1078?

**Comment by dennisklein** [comment] 2022-06-15 02:28
Or should I interpret this issue so that https://github.com/FairRootGroup/FairRoot/commit/efaff20a410c8994eef28b54d69449a90ba96f39
* is not good enough?
* must be formally released in order that you will/can use it?

**Comment by dennisklein** [comment] 2022-06-15 11:51
offtopic: @ChristianTackeGSI and I were just thinking, it would be nice to have a coffee together if there is a chance to meet in person. @klenze In any case and if you are interested, we have sent you a mattermost invitation where we could follow-up on this and have more direct communication in general (we also have dedicated FairRoot channel for discussions).

**Comment by klenze** [comment] 2022-06-22 15:50
efaff20 is fine. I think I was just a bit frustrated that it was not included in the april release. (But then again, that was a point release. 

I have accepted the mattermost invitation and logged in using my gsi gitlab credentials, but am not currently part of any teams? Did the invitation time out or something?

**Comment by dennisklein** [comment] 2022-11-11 17:43
5e156b2daa986517141f2f8120dff4549b434a94 scheduled for release in v18.8.

**Closed by dennisklein** 2022-11-11 17:43 UTC
