### ISSUE TITLE
FairRoot does not compile if GTest is not found.

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#511] opened 2017-04-05 07:59 UTC
Looks like GTest is now an hard requirement for FairRoot compilation. I get:

```
DEBUG:O2:0:   Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
DEBUG:O2:0:   GTEST_MAIN_LIBRARY)
DEBUG:O2:0: Call Stack (most recent call first):
DEBUG:O2:0:   /opt/boxen/homebrew/Cellar/cmake/3.7.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
DEBUG:O2:0:   /opt/boxen/homebrew/Cellar/cmake/3.7.1/share/cmake/Modules/FindGTest.cmake:194 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
DEBUG:O2:0:   fairmq/test/CMakeLists.txt:9 (find_package)
```

Is that intended?

**Comment by dennisklein** [comment] 2017-04-05 08:11
FairMQ tests now depend on GTest. You should be able to disable the building of (FairMQ) tests via the `BUILD_TESTING` cmake option from ctest, see https://cmake.org/cmake/help/v3.0/module/CTest.html. It is on by default.

**Comment by dennisklein** [comment] 2017-04-05 17:20
I have tried the `BUILD_TESTING` switch again to verify and it basically does not create the `test` target if switched off. In addition, FairMQ tests are not built as intended.

**Comment by ktf** [comment] 2017-04-05 21:29
IMHO you should be very careful when adding dependencies like this, breaking backward compatibility. As a user of FairRoot I would have expected that if GTest was not present, only the tests depending on GTest would have been disabled, not building the whole project.

**Comment by dennisklein** [comment] 2017-04-05 22:35
As a developer I will not take blame for breaking things in the `dev` branch... (Why do we have tools like `git revert` and `alibuild init` if we do not use them)

As a user I expect the FairRoot build system to be declarative about which components are built (cmake build switches).

The fact that targets are only built depending on the environment is in my opinion broken and dangerous. Unfortunately, as a single developer in a single PR I can only touch a limited number issues..

**Comment by ktf** [comment] 2017-04-05 22:53
I will not comment on your first statement, since I am leaving for holidays tomorrow and I do not want to start a flame war the night before... ;-)

For what concerns the second part, being declarative is fine, I am perfectly happy to specify `-DGTEST_ROOT=$GTEST_ROOT` if I want the GTest part being built. Actually I think every single dependency should be explicit and there should not be any environment involved (see issue #513). However, if I do not specify a given external, all its dependencies should be turned off. Having to different places which control the same feature is dangerous and does not make any particular sense: 

- specifying `GTEST_ROOT` and `BUILD_TEST=NO` does not make any sense
- not specifying `GTEST_ROOT` and `BUILD_TEST=YES` does not work

So I remain of my idea that if GTEST_ROOT is not set, you should not build the tests depending on GTEST.

**Comment by dennisklein** [comment] 2017-04-10 13:09
> not specifying GTEST_ROOT and BUILD_TEST=YES does not work

Why not? FindGTest could have picked up GTest from system paths.

> Having two different places which control the same feature is dangerous (...)

* `*_ROOT`: *optional* path hints for `find_package` modules
* `BUILD_*`: build switches with default values

I do not see why we should break this CMake idiom. I also do not see how it is dangerous.

If I set `-DBUILD_TESTING=ON`, I will expect always the full test suite to be built and not just a subset implicitely depending on the environment. Giving `GTEST_ROOT` the same semantics as `BUILD_TESTING`, as you suggest, is IMHO problematic, because, as you said yourself, not all tests might depend on GTest and it makes the `GTEST_ROOT` variable mandatory.

> So I remain of my idea that if GTEST_ROOT is not set, you should not build the tests depending on GTEST.

You consider the O2 aliBuild environment only which is not the whole picture. I can see few rare usecases, where you might want to build depending on `*_FOUND` family of variables though, e.g. to provide alternative implementations.

**Comment by dennisklein** [comment] 2017-05-09 12:32
I guess this discussion has died. Therefore closing, but reopen any time.

**Closed by dennisklein** 2017-05-09 12:32 UTC

**Comment by ktf** [comment] 2017-05-09 13:06
I meant to reply but never found the time. Yes, indeed, I meant `GTEST_FOUND`, not `GTEST_ROOT`. If `GTEST_FOUND=NO` building tests should be disabled by default, IMHO, especially if this was the previous behaviour.
