### ISSUE TITLE
Problem with running jobs for FairMuone

### ISSUE THREAD

**Issue by emssay** [FairRootGroup/FairRoot#1485] opened 2024-02-01 09:53 UTC
**Describe the bug**
I installed FairMuone software. In order to install it I needed to previously install FairSoft and FairRoot. I followed instructions at the readme file on the web page: https://gitlab.cern.ch/mgoncerz/fairmuone/-/tree/WiP_0.13.0?ref_type=heads and also on official FairSoft and FairRoot pages. After my installation I tried to test the software.  I did source FairRootConfig.sh and after entered in macros folder (fairmuone) and tried to run: root -l 'runProductionJob.C("exampleProductionJob")' according to the instructions. This gave me an error: fatal error: 'fairlogger/Logger.h' file not found
#include <fairlogger/Logger.h>
This program should make an root file which stores certain histograms as a product of simulations for MUonE experiment. Also when I searched for fairlogger I could find it in my installation files.

**System information (please complete the following information):**
 - OS: Ubuntu 22.04
 - Compiler: GCC 11.4.0

**Comment by karabowi** [comment] 2024-02-02 16:13
Which FairSoft/FairRoot version did you install? You can check it by going to corresponding source directories and execute 'git branch'.

**Comment by fuhlig1** [comment] 2024-02-05 11:05
@emssay,

I did a quick check and installed MUonE on our Debian10 system which worked with a small change in the build system. I could run the macro afterwards without the error. Since the needed change in the build dsystem is probably due to a rather old compiler I will now test if I can compile without changes on Ubuntu 22.04.

**Comment by emssay** [comment] 2024-02-05 11:52
> Which FairSoft/FairRoot version did you install? You can check it by going to corresponding source directories and execute 'git branch'.

When I do git branch I get:
Fairsoft: * master
FairRoot: * dev

**Comment by emssay** [comment] 2024-02-05 11:54
> @emssay,
> 
> I did a quick check and installed MUonE on our Debian10 system which worked with a small change in the build system. I could run the macro afterwards without the error. Since the needed change in the build dsystem is probably due to a rather old compiler I will now test if I can compile without changes on Ubuntu 22.04.

Ok, when I installed FairMuone 2 weeks ago it worked well. Then I reinstalled my Root and it didn't work so I did a re-installation of entire FairMuone software and it was giving me the same error.

**Comment by fuhlig1** [comment] 2024-02-05 12:48
@emssay,

I have now also tried on Ubuntu 22.04 and I was able to run the macro. The produced ROOT file looks reasonable but I am not able to judge if the data makes sense.

I have used the following FairSoft and FairRoot versions 

FairSoft: nov22p1
FairRoot: dev

I am not 100% sure but I expect that the versions you used could be the cause of the problem. Normally the FairSoft master branch is only updated from time to time such that it contains normally an older state while FairRoot dev is the bleeding edge development branch which sometimes doesn't fit. This is why I would propose to use stable releases when not something else is needed. We check that these versions work together like the used versions mentioned above.

To get these versions you need to switch to the correct branch after cloning from the repository

```
git clone https://github.com/FairRootGroup/FairSoft.git
cd FairSoft
git checkout -b tag_nov22p1 nov22p1
```

 ```
git clone https://github.com/FairRootGroup/FairRoot.git
cd FairRoot
git checkout -b tag_v18.8.1 v18.8.1
```

The rest of the description at https://gitlab.cern.ch/mgoncerz/fairmuone/ looks reasonable and is what I did.

Hope this helps to solve the problem.

**Comment by fuhlig1** [comment] 2024-07-05 10:12
@emssay,

is your problem meanwhile solved?

**Comment by emssay** [comment] 2024-07-05 12:47
Hi, yes my problem was solved when I reinstalled the whole software
(Fairrrot + Fairmuone) week after I had the problem. Honestly I dont know
what exactly caused this problem and what fixed it.

**Comment by fuhlig1** [comment] 2024-07-08 09:28
Thanks for confirmation. I will close the issue now.

**Closed by fuhlig1** 2024-07-08 09:28 UTC
