### ISSUE TITLE
Running buggy macros lead to dump of huge amount of header source

### ISSUE THREAD

**Issue by bl0x** [FairRootGroup/FairRoot#519] opened 2017-04-05 15:21 UTC
When a broken/buggy macro is executed, a big dump of Fairroot header source code is printed. It is cumbersome to scroll up for finding the actual error message.

**Comment by dennisklein** [comment] 2017-04-05 15:26
Can you please provide an example with details when this happens?

**Comment by bl0x** [comment] 2017-04-05 16:14
I've tried running the tutorial1 included in fairroot. This is the beginning of the output:
--------------------------
Processing run_tutorial1.C...
[INFO   ] FairRootManager::OpenOutFile(".//tutorial1_TGeant3_pions.mc_p2.000_t0_n10.root")
[INFO   ] Media file used: /opt/fairroot/v-17.03/share/fairbase/examples/common/geometry/media.geo
[INFO   ] ==============  FairRunSim: Initialising simulation run ==============
Info in <TGeoManager::TGeoManager>: Geometry FAIRGeom, FAIR geometry created
[INFO   ] FairGeoMedia: Read media 

************************************************************* 
     initialisation for run id 1491408284
************************************************************* 
[INFO   ] -------------- Standard Config is called ------------------------------------
[INFO   ] ---User path for Configuration (g3libs.C) is used: /opt/fairroot/v-17.03/share/fairbase/examples/common/gconfig
[INFO   ] ---User path for Configuration (g3Config.C) is used: /opt/fairroot/v-17.03/share/fairbase/examples/common/gconfig
[INFO   ] ---User path for Cuts and Processes (SetCuts.C) is used: /opt/fairroot/v-17.03/share/fairbase/examples/common/gconfig
Loading Geant3 libraries ...
Loading Geant3 libraries ... finished
G__MCStackDict dictionary payload:48:10: fatal error: 'FairDetectorList.h' file not found
#include "FairDetectorList.h"           // for DetectorId
         ^
Error in <TInterpreter::AutoParse>: Error parsing payload code for class FairStack with content:

#line 1 "G__MCStackDict dictionary payload"

#ifndef G__VECTOR_HAS_CLASS_ITERATOR
  #define G__VECTOR_HAS_CLASS_ITERATOR 1
#endif

#define _BACKWARD_BACKWARD_WARNING_H
/********************************************************************************
 *    Copyright (C) 2014 GSI Helmholtzzentrum fuer Schwerionenforschung GmbH    *
 *                                                                              *
 *              This software is distributed under the terms of the             * 
 *         GNU Lesser General Public Licence version 3 (LGPL) version 3,        *  
 *                  copied verbatim in the file "LICENSE"                       *
-------------------
and then it goes on with a lot more text.

My (interesting part of the) environment is the following:
-------------------
SIMPATH=/opt/fairsoft/mar17-1
LD_LIBRARY_PATH=/opt/epics/base/lib/linux-x86_64:/opt/fairsoft/mar17-1/lib/root:/usr/lib/root:/opt/fairroot/v-17.03/lib:/opt/fairsoft/mar17-1/lib/root:/opt/fairsoft/mar17-1/lib
ROOT_INCLUDE_PATH=/opt/fairroot/v-17.03/include
ROOTSYS=/opt/fairsoft/mar17-1
VMCWORKDIR=/opt/fairroot/v-17.03/share/fairbase/examples
ROOT_LIBRARY_DIR=/opt/fairsoft/mar17-1/lib/root
FAIRROOTPATH=/opt/fairroot/v-17.03
ROOT_LIBRARIES=-L/opt/fairsoft/mar17-1/lib/root -lGui -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -pthread -lm -ldl -rdynamic
PYTHONPATH=/opt/fairsoft/mar17-1/lib:/opt/fairsoft/mar17-1/lib/root:/opt/fairsoft/mar17-1/lib/Geant4:/opt/fairsoft/mar17-1/lib/g4py
FAIRLIBDIR=/opt/fairroot/v-17.03/lib
ROOT_INCLUDE_DIR=/opt/fairsoft/mar17-1/include/root

**Comment by dennisklein** [comment] 2017-04-05 16:28
Thank you for your feedback, we will look into the issue.

Aside: In the section "Github flavored markdown" on https://guides.github.com/features/mastering-markdown/ you can find how to format verbatim blocks on github.

**Comment by fuhlig1** [comment] 2017-04-05 16:35
Hi Bastian,

this is not a feature of FairRoot but a feature of Root6 which compiles any macro before execution. If there is an error during the compilation you get the complete output. 
In your case the problem is the header file which are not found. Could you please try to add the path where your FairRoot includes are installed to the environment variable
ROOT_INCLUDE_DIR and try to run the macro again.

Ciao

Florian



Am 05.04.2017 um 18:14 schrieb Bastian Löher <notifications@github.com>:

**Comment by bl0x** [comment] 2017-04-05 16:49
Thanks for the hint. Is there an option in Root6 to turn this output off, because in most cases it is not helpful.

Apparently the missing header file is not installed into the main include dir, which in my case is /opt/fairroot/v-17.03/include. Instead it is located in the examples/common/mcstack directory, which does not get installed.

Adjusting the ROOT_INCLUDE_DIR did not help.

**Comment by dennisklein** [comment] 2017-04-05 18:35
@bl0x Once my PR is merged, this particular missing header file should be properly installed.

**Comment by dennisklein** [comment] 2017-05-09 12:36
Closing for inactivity. Pls reopen any time, if it is not yet resolved :)

**Closed by dennisklein** 2017-05-09 12:36 UTC
