### ISSUE TITLE
TList::Error-message when deleting `Init()`alized FairRunAna instance

### ISSUE THREAD

**Issue by BSali** [FairRootGroup/FairRoot#1108] opened 2021-09-17 09:34 UTC
Currently I noticed that I am  getting `Error in <TList::Clear>: A list is accessing an object (0x8fea8a0) already deleted (list name = Browsables)` whenever I delete an `Init()`ialized `FairRunAna` instance. This has **no** effect on successfully running FairROOT/PandaROOT scripts or tests.

**To Reproduce**
gcc: 8.4.0
FairSoft: nov20_patches
FairRoot: 18.6_patches

In an interactive ROOT session do:
```c++
FairRunAna *ana = new FairRunAna();
ana->SetSink(new FairRootFileSink("dummyTest.root"));
ana->Init();
delete ana;
.q
```
After .q I receive this error message. Without  `Init()`ializing the ana instance or without deleting the ana instance the session will end without this message.

I believe this error message comes from deleting the fTask object in `~FairRun()`, after fTask is added to gROOTs ListOfBrowsables() in `FairRunAna::Init()`. Commenting out the `delete fTask` statement in `~FairRun()` has removed the error message for me.

However, I might by quite wrong about that. So far I was not able to reproduce this error-message for FairSoft_may18 and FairROOT-v18.2, even though the same fTask deletion  and addition to the ListOfBrowsables() of gROOT takes place. Therefore I would expect to see the Error-Message there as well, if my assumption would be correct, but I do not see it there.

A PandaROOT colleague has confirmed that he also gets this Error-message with an up-to-date FairSoft/ROOT/PandaROOT setup, hence I would believe that it is not due to a wrongly configured FairSoft/ROOT/PandaROOT system just on my side. 
Have you experienced this Error-message before?

**Comment by dennisklein** [comment] 2021-09-17 18:22
Thank you very much for the bug report! I can confirm the bug also being present in the current `dev` branch (7da3d476).

Your analysis is spot-on. While `FairRunAna` correctly deletes `fTask` because it keeps ownership even after adding `fTask` to the global browsables list (`gROOT->GetListOfBrowsables()->IsOwner() == false`), it should however also remove it from this list before deleting it.

BTW, the [`TList::Clear()` implementation](https://github.com/root-project/root/blob/87a998d48803bc207288d90038e60ff148827664/core/cont/src/TList.cxx#L443-L445) that prints this error message is highly interesting, since it dereferences a pointer to deallocated memory and then literally prints that it was illegal to do so 🤣 🙈

**Comment by ChristianTackeGSI** [comment] 2022-10-07 12:28
I think, this might have been fixed in ac9dba598eb911b7bc344b16a0231dd7266990bd

Do you have a chance of either trying this on the dev branch or backporting this single fix to a local FairRoot version?

@dennisklein Should we backport this to 18.x?

**Comment by PALoizeau** [comment] 2022-10-17 15:02
I can confirm that on the Cbmroot side this commit seems to make our temp-fix mentioned in the other issue obsolete: the Error message is gone and I did not see the segfault in the 3 CI iterations I did. Reverting the change on the Fairroot side without doing the same on the Cbmroot side brings back the error message as expected (did not have the time to make enough tests to trigger the segfault).

I guess it would still be good to know if this fixes both observed problems also for Panda.

To be confirmed by @fuhlig1:  nonetheless I think there would be interest from our side to have it in the release/patch we will use next (probably the latest 18.6.y, @fuhlig1 is the one who knows best which we will pick), as we are still creating new FairRunAna based classes to provide new users with easy entry points to our analysis sequence, which would all require my temp-fix. 
The two commits clearing the ownership of the Source/Sink pointers (d75ca6b8a694cf9cc3c83093bab64e0087d2d271 and cd21c6b52e44188ec1a55cb5cd1e1279725b342b) may also be interesting in case they are not too coupled to other developments, as the destructors of our FairRun derived classes brought a few double-delete errors at session exit similar to #1218 until we realized the Manager was keeping hold of them and we should not clear them.

**Comment by dennisklein** [comment] 2022-11-11 18:16
f9f164810, 65cf2d41b, fef881b16 scheduled for release in v18.8.

**Closed by dennisklein** 2022-11-11 18:16 UTC
Labels: bug

**Comment by ChristianTackeGSI** [comment] 2022-11-12 09:55
I wonder, whether we should backport f9f1648108e58ca998cd0b8a0d67601440934ad0 to 18.6 as well?

**Comment by fuhlig1** [comment] 2022-11-14 08:07
Yes. Please port it also to the v18.6 branch since this is the version currently used by CBM.
