### ISSUE TITLE
ERROR CMAKE FAIRROOT MACOS 14 (SONOMA)

### ISSUE THREAD

**Issue by LeoFoorm** [FairRootGroup/FairRoot#1493] opened 2024-02-23 22:33 UTC
[log.txt](https://github.com/FairRootGroup/FairRoot/files/14390637/log.txt)

CMake Warning (dev) at CMakeLists.txt:76 (include):
  Policy CMP0145 is not set: The Dart and FindDart modules are removed.  Run
  "cmake --help-policy CMP0145" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /Users/leonardofernandezluna/FAIRROOT/test/cmake-3.29.0-rc2/Modules/Dart.cmake:47 (message):
  Policy CMP0145 is not set: The Dart and FindDart modules are removed.  Run
  "cmake --help-policy CMP0145" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:76 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /Users/leonardofernandezluna/FAIRROOT/test/cmake-3.29.0-rc2/Modules/Dart.cmake:57 (find_package):
  Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
  variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  CMake variable DART_ROOT is set to:

    DART_ROOT-NOTFOUND

  For compatibility, find_package is ignoring the variable, but code in a
  .cmake module might still use it.
Call Stack (most recent call first):
  CMakeLists.txt:76 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/modules/CheckCompiler.cmake:191 (EXEC_PROGRAM):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  CMakeLists.txt:80 (Check_Compiler)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found a Mac OS X System 14.2
-- Found GNU compiler collection
-- Fortran libraries found in /opt/homebrew/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin23/13/../../..
CMake Error at cmake/modules/FindROOT.cmake:94 (Math):
  Math cannot parse the expression: "6.30.02*10000 + 6.30.02*100 + 6.30.02":
  syntax error, unexpected exp_NUMBER, expecting end of file (5).
Call Stack (most recent call first):
  cmake/modules/FairMacros.cmake:431 (find_package)
  CMakeLists.txt:137 (find_package2)

CMake Error at cmake/modules/FindROOT.cmake:95 (Math):
  Math cannot parse the expression: "6.30.02*10000 + 6.30.02*100 + 6.30.02":
  syntax error, unexpected exp_NUMBER, expecting end of file (5).
Call Stack (most recent call first):
  cmake/modules/FairMacros.cmake:431 (find_package)
  CMakeLists.txt:137 (find_package2)

leonardofernandezluna@MacBook-Air-de-Leonardo build % cat log.txt
-- fairsoft-config found
-- ROOT::Core target added by hand.
-- ROOT::RIO target added by hand.
-- ROOT::Tree target added by hand.
-- ROOT::Rint target added by hand.
-- ROOT::Physics target added by hand.
-- ROOT::MathCore target added by hand.
-- ROOT::Thread target added by hand.
-- ROOT::Geom target added by hand.
-- ROOT::EG target added by hand.
-- ROOT::EGPythia6 target added by hand.
-- ROOT::Gpad target added by hand.
-- ROOT::Hist target added by hand.
-- ROOT::RHTTP target added by hand.
-- ROOT::Proof target added by hand.
-- ROOT::Net target added by hand.
-- ROOT::Matrix target added by hand.
-- ROOT::GeomPainter target added by hand.
-- ROOT::Graf3d target added by hand.
-- ROOT::Graf target added by hand.
-- ROOT::RooFit target added by hand.
-- ROOT::RooFitCore target added by hand.
-- ROOT::XMLParser target added by hand.
-- ROOT::XMLIO target added by hand.
-- ROOT::Eve target added by hand.
-- ROOT::RGL target added by hand.
-- ROOT::Gui target added by hand.
-- ROOT::Ged target added by hand.
-- ROOT::Gdml target added by hand.
-- Looking for IWYU... - Not found
-- dds location is /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
-- dds location is /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   
--   INSTALL PREFIX       /Users/leonardofernandezluna/FAIRROOT/build_fairroot (change with -DCMAKE_INSTALL_PREFIX=...)
--   
--   GLOBAL CXX STANDARD  c++17
--   
--   BUILD TYPE           CXX FLAGS
-- * RELWITHDEBINFO       -O2 -g -Wshadow 
--   NIGHTLY              -O2 -g -Wshadow -Wall -Wextra
--   RELEASE              -O2 -Wshadow 
--   DEBUG                -g -Wshadow  -fno-inline
--   DEBUGFULL            -g3 -fno-inline -Wnon-virtual-dtor -Wno-long-long -ansi -Wundef -Wcast-align -Wchar-subscripts -Wall -W -Wpointer-arith -Wformat-security -fno-exceptions -fno-check-new -fno-common
--   PROFILE              -g3 -fno-inline -ftest-coverage -fprofile-arcs -Wall -Wextra
--   
--   (Change the build type with -DCMAKE_BUILD_TYPE=...)
--   
--   DEPENDENCY FOUND     VERSION                   PREFIX
--   ROOT                 6.30.02 (>= 6.10.00)      /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   VMC                  2.0.0                     /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/include
--   FairLogger           1.11.1 (>= 1.2.0)         /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   fmt                  10.1.1 (>= 5.3.0)         /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   Pythia6              unknown                   /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   Pythia8              8.310                     /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   Protobuf             4.25.3                    /opt/homebrew
--   Flatbuffers          23.5.26                   /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   Geant3               4.2.0                     /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--                                           G3SYS: Geant3_SYSTEM_DIR-NOTFOUND
--   Geant4               11.2.0                    /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--                                 G4NEUTRONHPDATA: /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/share/Geant4/data/G4NDL4.7
--                                        G4LEDATA: /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/share/Geant4/data/G4EMLOW8.5
--                                G4LEVELGAMMADATA: /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/share/Geant4/data/PhotonEvaporation5.7
--                               G4RADIOACTIVEDATA: /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/share/Geant4/data/RadioactiveDecay5.6
--                                G4PARTICLEXSDATA: /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/share/Geant4/data/G4PARTICLEXS4.0
--                                       G4PIIDATA: /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/share/Geant4/data/G4PII1.3
--                               G4REALSURFACEDATA: /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/share/Geant4/data/RealSurface2.2
--                                    G4SAIDXSDATA: /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/share/Geant4/data/G4SAIDDATA2.0
--                                      G4ABLADATA: /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/share/Geant4/data/G4ABLA3.3
--                                      G4INCLDATA: /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/share/Geant4/data/G4INCL1.2
--                                G4ENSDFSTATEDATA: /Users/leonardofernandezluna/FAIRROOT/FairSoft/install/share/Geant4/data/G4ENSDFSTATE2.3
--   VGM                  5.2.0                     /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   Geant4VMC            6.5.0                     /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   GSL                  unknown                   
--   FairMQ               1.8.4 (>= 1.4.0)          /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   DDS                  3.8                       /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   Boost                1.83 (>= 1.67)            /Users/leonardofernandezluna/FAIRROOT/FairSoft/install
--   yaml-cpp             0.8.0                     /opt/homebrew
--   ClangFormat          17.0.6                    
--   
--   COMPONENT           BUILT?  INFO
--   Examples             YES    (default, disable with -DBUILD_EXAMPLES=OFF)
--   Doxygen              NO     (default, enable with -DBUILD_DOXYGEN=ON)
--   Unit tests           NO     (default, enable with -DBUILD_UNITTESTS=ON)
--   
-- Configuring incomplete, errors occurred!

**Comment by dennisklein** [comment] 2024-02-23 23:58
Hm, what is the error msg? The log file you attached appears incomplete.

**Comment by LeoFoorm** [comment] 2024-02-24 00:19
Sorry. I will upload it complete right now

**Comment by dennisklein** [comment] 2024-02-24 00:32
Thx, this is a duplicate of #1490.

For now, please use the branch `v18.8_patches`. A new point release `18.8.2` is in preparation as well.

**Comment by LeoFoorm** [comment] 2024-02-26 03:29
It works with Sonoma 14.2. Thank you very much.

**Closed** 2024-03-01 11:08 UTC
