### ISSUE TITLE
cmake Errors when building FairRoot v18.0.4 on Ubuntu

### ISSUE THREAD

**Issue by spflueger** [FairRootGroup/FairRoot#845] opened 2018-11-07 11:53 UTC
cmake throws tons of errors like (I just picked the last one) :
```
CMake Error at cmake/modules/ROOTMacros.cmake:352 (Add_Executable):
  Target "ex-lmd-mbs-sink" links to target "Boost::signals" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  examples/MQ/Lmd/CMakeLists.txt:93 (GENERATE_EXECUTABLE)
```

The FairSoft packages installed without problems and the `find_package(Boost)` call also finds the correct (FairSoft) boost.

I checked the examples/MQ/Lmd/CMakeLists.txt file, and saw that the Boost libraries are used strangely:
```cmake
Set(DEPENDENCIES
    FairMQ::FairMQ
    BaseMQ
    ${Boost_THREAD_LIBRARY}
    ${Boost_SYSTEM_LIBRARY}
    ${Boost_SERIALIZATION_LIBRARY}
    ${Boost_PROGRAM_OPTIONS_LIBRARY}
    MbsTutorial
    ExLmd
)
```
Normally the FindBoost cmake will export the libraries in the Boost:: namespace. Hence I would have expected the following lines 
```cmake
    Boost::thread
    Boost::system
    Boost::serialization
    Boost::program_options
```
Well, anyways it seems like some cmake configuration problem.

*Steps to reproduce the behavior:*
1. Install FairSoft may18 to ${FairSoft-Install} diectory
2. `export SIMPATH=${FairSoft-Install}`
3. git clone of tag 18.0.4 ...
4. `mkdir build && cd build`
5. `cmake .. -DCMAKE_INSTALL_PREFIX=${FairRoot-Install}`

I'm using this system and versions:
Ubuntu 18, FairSoft may18, FairRoot 18.0.4

**Comment by MohammadAlTurany** [comment] 2018-11-08 12:50
Hi @spflueger 

I  could not reproduce this on ubuntu 18.04 with gcc 8.0.1 could you please check which FairMQ version you have in FairSoft? Could you remove your CMakeCash.txt in FairRoot and try again?

best,

Mohammad

**Comment by spflueger** [comment] 2018-11-08 13:20
Hmm ok strange. Btw I'm using gcc 7.3.0, but i think that's irrelevant. The errors I get are all related to Boost, so this problem does not only occur with FairMQ. I have version 1.2.3 of FairMQ.
Maybe this helps:
>CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:279 (find_package)

My boost version (as of FairSoft) is 1.67
Deleting CMakeCache.txt does not help

**Comment by rbx** [comment] 2018-11-08 13:33
FairSoft should've installed CMake 3.11 already, which is the minimum in may18.
Instead of using your system cmake, try to rerun with `$SIMPATH/bin/cmake`

**Comment by spflueger** [comment] 2018-11-08 13:54
Yeah, using the cmake 3.11 from the external packages solves the problem. But why don't you use the library names exported by Boost? So instead of `${Boost_THREAD_LIBRARY}` use `Boost::thread`? (I think that way will also choose the correct build version libraries)

**Comment by MohammadAlTurany** [comment] 2018-11-08 14:10
This is from the time where we wanted to be sure that the same library is always used (with/without _mt). The whole cmake system in FairRoot will be modernised very soon (see PR #632) 
For now I will increase the required Cmake version number to 3.11 and close this issue.

**Comment by dennisklein** [comment] 2018-11-08 14:14
> I checked the examples/MQ/Lmd/CMakeLists.txt file, and saw that the Boost libraries are used strangely:

This is just the old way of doing things in CMake prior to version 3. (Nothing wrong about it, just a lower level interface than the imported target system)

> So instead of ${Boost_THREAD_LIBRARY} use Boost::thread?

A CMake modernization which also addresses this point is in the works.

The modern way of doing things comes also with some drawbacks in the case of Boost:

Since the imported Boost targets are defined by the FindBoost.cmake module shipped with CMake, one has to keep up with CMake versions to get the imported Boost:: targets for recent Boost versions.

**Comment by spflueger** [comment] 2018-11-08 14:14
@MohammadAlTurany  All right, thx

**Closed** 2018-11-14 15:46 UTC
